services:
  create-mysql-db:
    image: mysql:latest
    container_name: your_container_name_1
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_schema_name
    ports:
      - "@:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - your_network

  create-ubuntu-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: your_container_name_2
    ports:
      - "@:22"
      - "@:7777"
    volumes:
      - ./app:/opt/app
    environment:
      - TZ=Asia/Seoul
    restart: always
    networks:
      - your_network

networks:
  your_network:
    name: your_network
